# coding: utf-8

# flake8: noqa

"""
    Tower of Babel

    Our server helps out tagging STT raw segments as well as providing an interface for translation to the relevant professsionals.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: liad4231@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.nemesis_api import NemesisApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.status import Status
from swagger_client.models.text_file import TextFile
from swagger_client.models.translation_entry import TranslationEntry
