# coding: utf-8

"""
    Tower of Babel

    Our server helps out tagging STT raw segments as well as providing an interface for translation to the relevant professsionals.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: liad4231@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TextFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'source': 'str',
        'doc_time': 'int',
        'arrival_time': 'int',
        'content': 'str'
    }

    attribute_map = {
        'title': 'title',
        'source': 'source',
        'doc_time': 'doc_time',
        'arrival_time': 'arrival_time',
        'content': 'content'
    }

    def __init__(self, title=None, source=None, doc_time=None, arrival_time=None, content=None):  # noqa: E501
        """TextFile - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._source = None
        self._doc_time = None
        self._arrival_time = None
        self._content = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if source is not None:
            self.source = source
        if doc_time is not None:
            self.doc_time = doc_time
        if arrival_time is not None:
            self.arrival_time = arrival_time
        if content is not None:
            self.content = content

    @property
    def title(self):
        """Gets the title of this TextFile.  # noqa: E501


        :return: The title of this TextFile.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this TextFile.


        :param title: The title of this TextFile.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def source(self):
        """Gets the source of this TextFile.  # noqa: E501


        :return: The source of this TextFile.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this TextFile.


        :param source: The source of this TextFile.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def doc_time(self):
        """Gets the doc_time of this TextFile.  # noqa: E501


        :return: The doc_time of this TextFile.  # noqa: E501
        :rtype: int
        """
        return self._doc_time

    @doc_time.setter
    def doc_time(self, doc_time):
        """Sets the doc_time of this TextFile.


        :param doc_time: The doc_time of this TextFile.  # noqa: E501
        :type: int
        """

        self._doc_time = doc_time

    @property
    def arrival_time(self):
        """Gets the arrival_time of this TextFile.  # noqa: E501


        :return: The arrival_time of this TextFile.  # noqa: E501
        :rtype: int
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time):
        """Sets the arrival_time of this TextFile.


        :param arrival_time: The arrival_time of this TextFile.  # noqa: E501
        :type: int
        """

        self._arrival_time = arrival_time

    @property
    def content(self):
        """Gets the content of this TextFile.  # noqa: E501


        :return: The content of this TextFile.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this TextFile.


        :param content: The content of this TextFile.  # noqa: E501
        :type: str
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TextFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
