# coding: utf-8

"""
    Tower of Babel

    Our server helps out tagging STT raw segments as well as providing an interface for translation to the relevant professsionals.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: liad4231@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.nemesis_api import NemesisApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNemesisApi(unittest.TestCase):
    """NemesisApi unit test stubs"""

    def setUp(self):
        self.api = api.nemesis_api.NemesisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_raw_attachment_by_id(self):
        """Test case for get_raw_attachment_by_id

        """
        pass

    def test_get_raw_document_by_id(self):
        """Test case for get_raw_document_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
