# coding: utf-8

"""
    Tower of Babel

    Our server helps out tagging STT raw segments as well as providing an interface for translation to the relevant professsionals.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: liad4231@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.text_file import TextFile  # noqa: E501
from swagger_client.rest import ApiException


class TestTextFile(unittest.TestCase):
    """TextFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextFile(self):
        """Test TextFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.text_file.TextFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
